sudo: required
services:
  - docker
env:
  - SHA=${git rev-parse HEAD}
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl ... # command that is from encryption on travis cli for decryption service-account file
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-serive-account --key-file service-account.json
  - gcloud config set project PROJ_ID
  - gcloud config set comput/zone ZONE
  - gcloud container clusters get-credentials fib-calc-k8s
  - echo "$DOCKER_PASSWORD" | docker login - u "$DOCKER_USERNAME" --password
  - docker build -t kamilesta/client-test -f ./client/Dockerfile.dev

script:
  - docker run CI=true kamilesta/client-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master